name: Lighthouse CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install -g @lhci/cli@0.13.x 
      - name: Run Lighthouse CI
        run: lhci autorun --url=https://www.rare1k.space
